function translateText(language) {

    var headerNav1      = "";
    var headerNav2      = "";
    var headerNav3      = "";
    var headerNav4      = "";
    var headerNav5      = "";
    var headerDiv1      = "";
    var mainNosotros1   = "";
    var mainNosotros2   = "";
    var mainQuote1      = "";
    var mainServicios1  = "";
    var mainServicios2  = "";
    var mainServicios3  = "";
    var mainServicios4  = "";
    var mainServicios5  = "";
    var mainServicios6  = "";
    var mainServicios7  = "";
    var mainServicios8  = "";
    var mainServicios9  = "";
    var mainServicios10 = "";
    var mainServicios11 = "";
    var mainServicios12 = "";
    var mainServicios13 = "";
    var mainServicios14 = "";
    var mainServicios15 = "";
    var mainServicios16 = "";
    var mainServicios17 = "";
    var mainServicios18 = "";
    var mainServicios19 = "";
    var mainServicios20 = "";
    var mainServicios21 = "";
    var mainServicios22 = "";
    var mainServicios23 = "";
    var mainServicios24 = "";
    var mainMision1     = "";
    var mainMision2     = "";
    var mainMision3     = "";
    var mainMision4     = "";
    var mainMision5     = "";
    var mainMision6     = "";
    var mainEsquema1    = "";
    var mainEsquema2    = "";
    var mainEsquema3    = "";
    var mainEsquema4    = "";
    var mainEsquema5    = '';
    var mainEsquema6    = "";
    var mainEsquema7    = "";
    var mainEsquema8    = "";
    var mainEsquema9    = "";
    var mainBeneficios1 = "";
    var mainBeneficios2 = "";
    var mainBeneficios3 = "";
    var mainBeneficios4 = "";
    var mainBeneficios5 = "";
    var mainBeneficios6 = "";
    var mainBeneficios7 = "";
    var mainUbicacion1  = "";
    var mainUbicacion2  = "";
    var mainContact1    = "";
    var mainContact2    = "";
    var mainContact3    = "";
    var mainContact4    = "";
    var mainContact5    = "";
    var mainContact6    = "";
    var mainContact7    = "";
    var mainContact8    = "";
    var mainContact9    = "";
    var footer1         = ""; 

    if (language === 'en') {
        headerNav1 = LANG.HEADER.NAVBAR.TEXTO1.EN;
        headerNav2 = LANG.HEADER.NAVBAR.TEXTO2.EN;
        headerNav3 = LANG.HEADER.NAVBAR.TEXTO3.EN;
        headerNav4 = LANG.HEADER.NAVBAR.TEXTO4.EN;
        headerNav5 = LANG.HEADER.NAVBAR.TEXTO5.EN;
        headerDiv1 = LANG.HEADER.DIV.TEXTO1.EN;
        mainNosotros1 = LANG.MAIN.NOSOTROS.TEXT1.EN;
        mainNosotros2 = LANG.MAIN.NOSOTROS.TEXT2.EN;
        mainQuote1 = LANG.MAIN.QUOTE.TEXT1.EN;
        mainServicios1 = LANG.MAIN.SERVICIOS.TEXT1.EN;
        mainServicios2 = LANG.MAIN.SERVICIOS.TEXT2.EN;
        mainServicios3 = LANG.MAIN.SERVICIOS.TEXT3.EN;
        mainServicios4 = LANG.MAIN.SERVICIOS.TEXT4.EN;
        mainServicios5 = LANG.MAIN.SERVICIOS.TEXT5.EN;
        mainServicios6 = LANG.MAIN.SERVICIOS.TEXT6.EN;
        mainServicios7 = LANG.MAIN.SERVICIOS.TEXT7.EN;
        mainServicios8 = LANG.MAIN.SERVICIOS.TEXT8.EN;
        mainServicios9 = LANG.MAIN.SERVICIOS.TEXT9.EN;
        mainServicios10 = LANG.MAIN.SERVICIOS.TEXT10.EN;
        mainServicios11 = LANG.MAIN.SERVICIOS.TEXT11.EN;
        mainServicios12 = LANG.MAIN.SERVICIOS.TEXT12.EN;
        mainServicios13 = LANG.MAIN.SERVICIOS.TEXT13.EN;
        mainServicios14 = LANG.MAIN.SERVICIOS.TEXT14.EN;
        mainServicios15 = LANG.MAIN.SERVICIOS.TEXT15.EN;
        mainServicios16 = LANG.MAIN.SERVICIOS.TEXT16.EN;
        mainServicios17 = LANG.MAIN.SERVICIOS.TEXT17.EN;
        mainServicios18 = LANG.MAIN.SERVICIOS.TEXT18.EN;
        mainServicios19 = LANG.MAIN.SERVICIOS.TEXT19.EN;
        mainServicios20 = LANG.MAIN.SERVICIOS.TEXT20.EN;
        mainServicios21 = LANG.MAIN.SERVICIOS.TEXT21.EN;
        mainServicios22 = LANG.MAIN.SERVICIOS.TEXT22.EN;
        mainServicios23 = LANG.MAIN.SERVICIOS.TEXT23.EN;
        mainServicios24 = LANG.MAIN.SERVICIOS.TEXT24.EN;
        mainMision1 = LANG.MAIN.MISION.TEXT1.EN;
        mainMision2 = LANG.MAIN.MISION.TEXT2.EN;
        mainMision3 = LANG.MAIN.MISION.TEXT3.EN;
        mainMision4 = LANG.MAIN.MISION.TEXT4.EN;
        mainMision5 = LANG.MAIN.MISION.TEXT5.EN;
        mainMision6 = LANG.MAIN.MISION.TEXT6.EN;
        mainEsquema1 = LANG.MAIN.ESQUEMA.TEXT1.EN;
        mainEsquema2 = LANG.MAIN.ESQUEMA.TEXT2.EN;
        mainEsquema3 = LANG.MAIN.ESQUEMA.TEXT3.EN;
        mainEsquema4 = LANG.MAIN.ESQUEMA.TEXT4.EN;
        mainEsquema5 = LANG.MAIN.ESQUEMA.TEXT5.EN;
        mainEsquema6 = LANG.MAIN.ESQUEMA.TEXT6.EN;
        mainEsquema7 = LANG.MAIN.ESQUEMA.TEXT7.EN;
        mainEsquema8 = LANG.MAIN.ESQUEMA.TEXT8.EN;
        mainEsquema9 = LANG.MAIN.ESQUEMA.TEXT9.EN;
        mainBeneficios1 = LANG.MAIN.BENEFICIOS.TEXT1.EN;
        mainBeneficios2 = LANG.MAIN.BENEFICIOS.TEXT2.EN;
        mainBeneficios3 = LANG.MAIN.BENEFICIOS.TEXT3.EN;
        mainBeneficios4 = LANG.MAIN.BENEFICIOS.TEXT4.EN;
        mainBeneficios5 = LANG.MAIN.BENEFICIOS.TEXT5.EN;
        mainBeneficios6 = LANG.MAIN.BENEFICIOS.TEXT6.EN;
        mainBeneficios7 = LANG.MAIN.BENEFICIOS.TEXT7.EN;
        mainUbicacion1 = LANG.MAIN.UBICACION.TEXT1.EN;
        mainUbicacion2 = LANG.MAIN.UBICACION.TEXT2.EN;
        mainContact1 = LANG.MAIN.CONTACT.TEXT1.EN;
        mainContact2 = LANG.MAIN.CONTACT.TEXT2.EN;
        mainContact3 = LANG.MAIN.CONTACT.TEXT3.EN;
        mainContact4 = LANG.MAIN.CONTACT.TEXT4.EN;
        mainContact5 = LANG.MAIN.CONTACT.TEXT5.EN;
        mainContact6 = LANG.MAIN.CONTACT.TEXT6.EN;
        mainContact7 = LANG.MAIN.CONTACT.TEXT7.EN;
        mainContact8 = LANG.MAIN.CONTACT.TEXT8.EN;
        mainContact9 = LANG.MAIN.CONTACT.TEXT9.EN;
        footer1 = LANG.FOOTER.TEXT1.EN;
    } else {
        headerNav1 = LANG.HEADER.NAVBAR.TEXTO1.ES;
        headerNav2 = LANG.HEADER.NAVBAR.TEXTO2.ES;
        headerNav3 = LANG.HEADER.NAVBAR.TEXTO3.ES;
        headerNav4 = LANG.HEADER.NAVBAR.TEXTO4.ES;
        headerNav5 = LANG.HEADER.NAVBAR.TEXTO5.ES;
        headerDiv1 = LANG.HEADER.DIV.TEXTO1.ES;
        mainNosotros1 = LANG.MAIN.NOSOTROS.TEXT1.ES;
        mainNosotros2 = LANG.MAIN.NOSOTROS.TEXT2.ES;
        mainQuote1 = LANG.MAIN.QUOTE.TEXT1.ES;
        mainServicios1 = LANG.MAIN.SERVICIOS.TEXT1.ES;
        mainServicios2 = LANG.MAIN.SERVICIOS.TEXT2.ES;
        mainServicios3 = LANG.MAIN.SERVICIOS.TEXT3.ES;
        mainServicios4 = LANG.MAIN.SERVICIOS.TEXT4.ES;
        mainServicios5 = LANG.MAIN.SERVICIOS.TEXT5.ES;
        mainServicios6 = LANG.MAIN.SERVICIOS.TEXT6.ES;
        mainServicios7 = LANG.MAIN.SERVICIOS.TEXT7.ES;
        mainServicios8 = LANG.MAIN.SERVICIOS.TEXT8.ES;
        mainServicios9 = LANG.MAIN.SERVICIOS.TEXT9.ES;
        mainServicios10 = LANG.MAIN.SERVICIOS.TEXT10.ES;
        mainServicios11 = LANG.MAIN.SERVICIOS.TEXT11.ES;
        mainServicios12 = LANG.MAIN.SERVICIOS.TEXT12.ES;
        mainServicios13 = LANG.MAIN.SERVICIOS.TEXT13.ES;
        mainServicios14 = LANG.MAIN.SERVICIOS.TEXT14.ES;
        mainServicios15 = LANG.MAIN.SERVICIOS.TEXT15.ES;
        mainServicios16 = LANG.MAIN.SERVICIOS.TEXT16.ES;
        mainServicios17 = LANG.MAIN.SERVICIOS.TEXT17.ES;
        mainServicios18 = LANG.MAIN.SERVICIOS.TEXT18.ES;
        mainServicios19 = LANG.MAIN.SERVICIOS.TEXT19.ES;
        mainServicios20 = LANG.MAIN.SERVICIOS.TEXT20.ES;
        mainServicios21 = LANG.MAIN.SERVICIOS.TEXT21.ES;
        mainServicios22 = LANG.MAIN.SERVICIOS.TEXT22.ES;
        mainServicios23 = LANG.MAIN.SERVICIOS.TEXT23.ES;
        mainServicios24 = LANG.MAIN.SERVICIOS.TEXT24.ES;
        mainMision1 = LANG.MAIN.MISION.TEXT1.ES;
        mainMision2 = LANG.MAIN.MISION.TEXT2.ES;
        mainMision3 = LANG.MAIN.MISION.TEXT3.ES;
        mainMision4 = LANG.MAIN.MISION.TEXT4.ES;
        mainMision5 = LANG.MAIN.MISION.TEXT5.ES;
        mainMision6 = LANG.MAIN.MISION.TEXT6.ES;
        mainEsquema1 = LANG.MAIN.ESQUEMA.TEXT1.ES;
        mainEsquema2 = LANG.MAIN.ESQUEMA.TEXT2.ES;
        mainEsquema3 = LANG.MAIN.ESQUEMA.TEXT3.ES;
        mainEsquema4 = LANG.MAIN.ESQUEMA.TEXT4.ES;
        mainEsquema5 = LANG.MAIN.ESQUEMA.TEXT5.ES;
        mainEsquema6 = LANG.MAIN.ESQUEMA.TEXT6.ES;
        mainEsquema7 = LANG.MAIN.ESQUEMA.TEXT7.ES;
        mainEsquema8 = LANG.MAIN.ESQUEMA.TEXT8.ES;
        mainEsquema9 = LANG.MAIN.ESQUEMA.TEXT9.ES;
        mainBeneficios1 = LANG.MAIN.BENEFICIOS.TEXT1.ES;
        mainBeneficios2 = LANG.MAIN.BENEFICIOS.TEXT2.ES;
        mainBeneficios3 = LANG.MAIN.BENEFICIOS.TEXT3.ES;
        mainBeneficios4 = LANG.MAIN.BENEFICIOS.TEXT4.ES;
        mainBeneficios5 = LANG.MAIN.BENEFICIOS.TEXT5.ES;
        mainBeneficios6 = LANG.MAIN.BENEFICIOS.TEXT6.ES;
        mainBeneficios7 = LANG.MAIN.BENEFICIOS.TEXT7.ES;
        mainUbicacion1 = LANG.MAIN.UBICACION.TEXT1.ES;
        mainUbicacion2 = LANG.MAIN.UBICACION.TEXT2.ES;
        mainContact1 = LANG.MAIN.CONTACT.TEXT1.ES;
        mainContact2 = LANG.MAIN.CONTACT.TEXT2.ES;
        mainContact3 = LANG.MAIN.CONTACT.TEXT3.ES;
        mainContact4 = LANG.MAIN.CONTACT.TEXT4.ES;
        mainContact5 = LANG.MAIN.CONTACT.TEXT5.ES;
        mainContact6 = LANG.MAIN.CONTACT.TEXT6.ES;
        mainContact7 = LANG.MAIN.CONTACT.TEXT7.ES;
        mainContact8 = LANG.MAIN.CONTACT.TEXT8.ES;
        mainContact9 = LANG.MAIN.CONTACT.TEXT9.ES;
        footer1 = LANG.FOOTER.TEXT1.ES; 
    }
        
    $("#hnav1").html(headerNav1);
    $("#hnav2").html(headerNav2);
    $("#hnav3").html(headerNav3);
    $("#hnav4").html(headerNav4);
    $("#hnav5").html(headerNav5);
    $("#hdiv1").html(headerDiv1);
    $("#mnosotros1").html(mainNosotros1);
    $("#mnosotros2").html(mainNosotros2);
    $("#mquote1").html(mainQuote1);
    $("#mservicios1").html(mainServicios1);
    $("#mservicios2").html(mainServicios2);
    $("#mservicios3").html(mainServicios3);
    $("#mservicios4").html(mainServicios4);
    $("#mservicios5").html(mainServicios5);
    $("#mservicios6").html(mainServicios6);
    $("#mservicios7").html(mainServicios7);
    $("#mservicios8").html(mainServicios8);
    $("#mservicios9").html(mainServicios9);
    $("#mservicios10").html(mainServicios10);
    $("#mservicios11").html(mainServicios11);
    $("#mservicios12").html(mainServicios12);
    $("#mservicios13").html(mainServicios13);
    $("#mservicios14").html(mainServicios14);
    $("#mservicios15").html(mainServicios15);
    $("#mservicios16").html(mainServicios16);
    $("#mservicios17").html(mainServicios17);
    $("#mservicios18").html(mainServicios18);
    $("#mservicios19").html(mainServicios19);
    $("#mservicios20").html(mainServicios20);
    $("#mservicios21").html(mainServicios21);
    $("#mservicios22").html(mainServicios22);
    $("#mservicios23").html(mainServicios23);
    $("#mservicios24").html(mainServicios24);
    $("#mmision1").html(mainMision1);
    $("#mmision2").html(mainMision2);
    $("#mmision3").html(mainMision3);
    $("#mmision4").html(mainMision4);
    $("#mmision5").html(mainMision5);
    $("#mmision6").html(mainMision6);
    $("#mesquema1").html(mainEsquema1);
    $("#mesquema2").html(mainEsquema2);
    $("#mesquema3").html(mainEsquema3);
    $("#mesquema4").html(mainEsquema4);
    $("#mesquema5").html(mainEsquema5);
    $("#mesquema6").html(mainEsquema6);
    $("#mesquema7").html(mainEsquema7);
    $("#mesquema8").html(mainEsquema8);
    $("#mesquema9").html(mainEsquema9);
    $("#mbefeneficios1").html(mainBeneficios1);
    $("#mbefeneficios2").html(mainBeneficios2);
    $("#mbefeneficios3").html(mainBeneficios3);
    $("#mbefeneficios4").html(mainBeneficios4);
    $("#mbefeneficios5").html(mainBeneficios5);
    $("#mbefeneficios6").html(mainBeneficios6);
    $("#mbefeneficios7").html(mainBeneficios7);
    $("#mubicacion1").html(mainUbicacion1);
    $("#mubicacion2").html(mainUbicacion2);
    $("#mcontacto1").html(mainContact1);
    $("#mcontacto2").html(mainContact2);
    $("#mcontacto3").html(mainContact3);
    $("#mcontacto4").html(mainContact4);
    $("#mcontacto5").html(mainContact5);
    $("#mcontacto6").html(mainContact6);
    $("#mcontacto7").html(mainContact7);
    $("#mcontacto8").html(mainContact8);
    $("#mcontacto9").html(mainContact9);
    $("#fprivacidad1").html(footer1);
}     